### ISSUE TITLE
should rename to "leaky" since you keep leaking security info 🥱

### ISSUE THREAD

**Issue by Reecepbcups** [notional-labs/spammy#22]
🥱 2nd time in 30 days

also shouldn't ctrlFelix get credit? I don't see his credit anywhere

**Comment by faddat** [comment]
keep it classy strangelove

**Comment by faddat** [comment]
Please also note, @reecepbcups that the ceo of strangelove labs, Jack Zampolin, said that there was no security issue.  I think he is your boss, so I'm not sure what you felt was disclosed, for the record, here's his statement on that:

https://x.com/gadikian/status/1722311165378986042?s=20

And here is Zarko (CTO Informal Systems) statement on p2p storms:

https://x.com/gadikian/status/1722311392123048166?s=20

In situations where the interchain foundation's contractors deny an issue that I feel is proven, I will continue to do the only possible mitigation:

direct disclosure to affected parties (the cosmos community)

this is in keeping with best practices in such matters.
